AWS_ACCESS_KEY: "AKIAJXSU5B5ZBFX7NK5Q"

AWS_SECRET_KEY: "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"

AWS_BUCKET: "studentbox"

AWS_REGION: "us-east-1"

SECRET_KEY: sk_test_y0fLB0XVdHoIehSqSa3VVKL7

PUBLISHABLE_KEY: pk_test_b2wlEtJKMlCeS0qj3uViGFLz